### ISSUE TITLE
No Instagram support

### ISSUE THREAD

**Issue by jasperroloff** [shariarbd/CSS3-Hexagon-Buttons#2]
Very nice work! I've just a little problem when I wan't to display an Instagram-button:
When using 
`<a class="hb-xs-margin" href="#"><span class="hb hb-xs hb-instagram"><i class="fa fa-instagram"></i></span></a>` 
there is an Instagram icon displayed but it is green and it's colors don't look like Instagram. 
Would be nice if there is a fix. Thanks!

**Comment by shariarbd** [comment]
Hi, 
I am a bit busy :( hope with in 3 or 4 days , you will get it
thanks for understanding :)

**Comment by shariarbd** [comment]
Hi, 
Dark Blue Color has been added for Instagram. If you need any other color, please open the hexagons.css file and go to the bottom and change the color accordingly as your requirements.
Thanks
